-- This module is the root of the ZilberPinkConjectureCanonicalLaneLean Lean proof package.
import ZilberPinkConjectureCanonicalLaneLean.Basic
import ZilberPinkConjectureCanonicalLaneLean.SourcePackage
import ZilberPinkConjectureCanonicalLaneLean.SourceDependencies
import ZilberPinkConjectureCanonicalLaneLean.Formalization
import ZilberPinkConjectureCanonicalLaneLean.ReviewerBridge
import ZilberPinkConjectureCanonicalLaneLean.TheoremStatement
import ZilberPinkConjectureCanonicalLaneLean.MathlibObjects
import ZilberPinkConjectureCanonicalLaneLean.AdmissibleClass
import ZilberPinkConjectureCanonicalLaneLean.Projection
import ZilberPinkConjectureCanonicalLaneLean.BridgeLemmas
import ZilberPinkConjectureCanonicalLaneLean.GateLemmas
import ZilberPinkConjectureCanonicalLaneLean.FinalTheorem
import ZilberPinkConjectureCanonicalLaneLean.MathlibStatement
